FROM python:3.9-slim

WORKDIR /app

# 1. Instalar dependencias del sistema
RUN apt-get update && apt-get install -y gcc && rm -rf /var/lib/apt/lists/*

# 2. Copiar e instalar dependencias
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# 3. Copiar aplicación
COPY app/ /app

# Exponer el puerto en el que la aplicación FastAPI correrá
EXPOSE 8000

# Iniciar FastAPI con Uvicorn (en lugar de usar 'python main.py')
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

